version: '3'
services:
  sample:
    build:
      context: .
    command: python3 script.py
    volumes:
      - .:/code
  precommit:
    build:
      context: .
      dockerfile: Dockerfile.precommit
    volumes:  
      - .:/precommit
      - ./.git:/tmp/.git
      - ~/.gitconfig:/root/.gitconfig
    tty: true
    stdin_open: true
