FROM nikolaik/python-nodejs:python3.9-nodejs15

RUN npm install -g lint-staged
RUN pip install black pylint

RUN mkdir /precommit && \
      cd /precommit && \
      git init .

WORKDIR /precommit

CMD sh -c "cd /tmp/.githooks && ls | xargs chmod +x && cd /tmp/.git/hooks && find ../../.githooks -type f -exec ln -sf {} /tmp/.git/hooks/ \; && echo 'githooks installed'"
